# Generated by Django 5.1.1 on 2024-10-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_questions', '0002_alter_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_nunmber',
            new_name='category_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(default='Lagos', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='counrty',
            field=models.CharField(default='Nigeria', max_length=200),
        ),
    ]
