# Generated by Django 5.1.1 on 2024-10-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_questions', '0003_rename_category_nunmber_category_category_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='counrty',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='produuct_category',
            new_name='product_category',
        ),
    ]
