# Generated by Django 5.1.1 on 2024-10-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_questions', '0004_rename_counrty_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
