# Generated by Django 5.1.1 on 2024-10-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_questions', '0006_category_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.CharField(default='Nigeria', max_length=200),
        ),
    ]
