# Generated by Django 5.1.1 on 2025-05-19 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_questions', '0007_category_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAudit',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('auidited_by', models.CharField(max_length=200)),
                ('total_score', models.IntegerField(default=0)),
                ('foundation_Skill_score', models.IntegerField(default=0)),
                ('commuication_skill_score', models.IntegerField(default=0)),
                ('probing_skill_score', models.IntegerField(default=0)),
                ('negotiation_skill_score', models.IntegerField(default=0)),
                ('closing_skill_score', models.IntegerField(default=0)),
                ('agent_disposition', models.CharField(max_length=200)),
                ('call_language', models.CharField(max_length=200)),
                ('call_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
