# Generated by Django 5.1.1 on 2025-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_questions', '0008_callaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='callaudit',
            name='country',
            field=models.CharField(default='Nigeria', max_length=200),
        ),
        migrations.AddField(
            model_name='callaudit',
            name='justification',
            field=models.TextField(null=True),
        ),
    ]
