# Generated by Django 5.1.1 on 2025-05-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_questions', '0009_callaudit_country_callaudit_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='callaudit',
            name='agent_id',
            field=models.CharField(default='00001', max_length=200),
        ),
    ]
