# Generated by Django 5.1.1 on 2025-05-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_questions', '0010_callaudit_agent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callaudit',
            name='country',
        ),
    ]
